version: "3"

services:
  app:
    image: verif-app:latest
    container_name: verif
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.XAuthority
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/tmp/.XAuthority
    network_mode: host
    ipc: host
